# Generated by Django 4.2.1 on 2023-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='pc')),
                ('idle_use_cost', models.IntegerField()),
                ('max_use_cost', models.IntegerField()),
                ('build_cost', models.IntegerField()),
                ('pcf_use', models.IntegerField()),
            ],
        ),
    ]
