# Generated by Django 4.2.1 on 2023-07-13 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='componentusage',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='components.component'),
        ),
    ]
