# Generated by Django 4.2.1 on 2023-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='component',
            name='pcf_use',
        ),
    ]
