# Generated by Django 4.2.1 on 2023-08-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_component_is_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='worse_case',
            new_name='worst_case',
        ),
    ]
