# Generated by Django 4.2.1 on 2023-08-31 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_rename_worse_case_component_worst_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='hosted_apps',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
