# Generated by Django 4.2.1 on 2023-08-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_rename_bad_case_idle_power_component_best_case_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentusage',
            unique_together={('component', 'calculation')},
        ),
        migrations.RemoveField(
            model_name='componentusage',
            name='use',
        ),
    ]
