# Generated by Django 4.2.1 on 2023-08-31 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_component_hosted_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentusage',
            name='server_years',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
            preserve_default=False,
        ),
    ]
