# Generated by Django 4.2.1 on 2023-09-07 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_componentusage_server_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentusage',
            name='emissions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
    ]
