# Generated by Django 4.2.1 on 2023-09-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_alter_component_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentusage',
            unique_together=set(),
        ),
    ]
